// THIS FILE IS AUTO-GENERATED BY scripts/generate-components-index.js - DO NOT EDIT MANUALLY

// default exports for components in this folder
export { default as Dictionary } from "./Dictionary.svelte";
export { default as Forvo } from "./Forvo.svelte";
export { default as Thesaurus } from "./Thesaurus.svelte";
export { default as Zoom } from "./Zoom.svelte";

