// THIS FILE IS AUTO-GENERATED BY scripts/generate-components-index.js - DO NOT EDIT MANUALLY

// default exports for components in this folder
export { default as Teacher } from "./Teacher.svelte";
export { default as Zoom } from "./Zoom.svelte";

