// THIS FILE IS AUTO-GENERATED BY scripts/generate-components-index.js - DO NOT EDIT MANUALLY

// folder re-exports (export everything from these folders)
export * from "./students/index.js";
export * from "./teachers/index.js";

// default exports for components in this folder
export { default as Content } from "./Content.svelte";
export { default as Dashboard } from "./Dashboard.svelte";
export { default as Legal } from "./Legal.svelte";
export { default as Lessons } from "./Lessons.svelte";
export { default as Promo } from "./Promo.svelte";
export { default as Settings } from "./Settings.svelte";
export { default as Tasks } from "./Tasks.svelte";
export { default as TutorialEl } from "./TutorialEl.svelte";
export { default as Words } from "./Words.svelte";
