// THIS FILE IS AUTO-GENERATED BY scripts/generate-components-index.js - DO NOT EDIT MANUALLY

// re-export TS/JS modules from this folder
export * from "./theme";
export * from "./types";

// default exports for components in this folder
export { default as Body } from "./Body.svelte";
