// THIS FILE IS AUTO-GENERATED BY scripts/generate-components-index.js - DO NOT EDIT MANUALLY

// folder re-exports (export everything from these folders)
export * from "./anchor";
export * from "./blockquote";
export * from "./descriptionlist";
export * from "./heading";
export * from "./paragraph";
export * from "./secondary";
