// THIS FILE IS AUTO-GENERATED BY scripts/generate-components-index.js - DO NOT EDIT MANUALLY

// folder re-exports (export everything from these folders)
export * from "./anchor";
export * from "./body";
export * from "./display";
export * from "./heading";
export * from "./headline";
export * from "./label";
export * from "./paragraph";
export * from "./secondary";
export * from "./title";

