// THIS FILE IS AUTO-GENERATED BY scripts/generate-components-index.js - DO NOT EDIT MANUALLY

// default exports for components in this folder
export { default as Account } from "./Account.svelte";
export { default as Custom } from "./Custom.svelte";
export { default as Money } from "./Money.svelte";
export { default as Notifications } from "./Notifications.svelte";
export { default as Security } from "./Security.svelte";
export { default as Teacher } from "./Teacher.svelte";
