// THIS FILE IS AUTO-GENERATED BY scripts/generate-components-index.js - DO NOT EDIT MANUALLY

// default exports for components in this folder
export { default as EmptySpace } from "./EmptySpace.svelte";
export { default as FullPage } from "./FullPage.svelte";

