// THIS FILE IS AUTO-GENERATED BY scripts/generate-components-index.js - DO NOT EDIT MANUALLY

// default exports for components in this folder
export { default as Paginator } from "./Paginator.svelte";
export { default as SortDate } from "./SortDate.svelte";
export { default as Table } from "./Table.svelte";
export { default as TableBody } from "./TableBody.svelte";
export { default as TableCell } from "./TableCell.svelte";
export { default as TableFooter } from "./TableFooter.svelte";
export { default as TableHead } from "./TableHead.svelte";
export { default as TableHeadCell } from "./TableHeadCell.svelte";
export { default as TableRow } from "./TableRow.svelte";
export { default as TableRowWithMorph } from "./TableRowWithMorph.svelte";
